### ISSUE TITLE
新活动

### ISSUE THREAD

**Issue by ahlifei** [CaoZ/JD-Coin#16]
https://m.jr.jd.com/udc-active/2017/baitiao0717/html/index.html?utm_source=Android&utm_term=wxfriends    发现一个新活动，可以领取小金库红包

**Comment by CaoZ** [comment]
是这个页面吗? 没有找到领红包的地方呢

![img_3227](https://user-images.githubusercontent.com/1962293/28492420-0c65ce0e-6f36-11e7-82fe-88c8c251d721.PNG)
