### ISSUE TITLE
QQ方式无法登录了

### ISSUE THREAD

**Issue by riverai** [CaoZ/JD-Coin#17]
提示提交参数错误，我估计大家都这样吧。

**Comment by CaoZ** [comment]
我刚试了下，是可以登录的。不过你这种情况以前也出现过，最后自己恢复正常了，原因不明，可能跟具体的账号有关系...

你的情况是不是跟 [这里](https://github.com/CaoZ/JD-Coin/issues/2#issuecomment-297640717) 的情况类似呢?

**Comment by riverai** [comment]
确实是这样的.......

**Comment by riverai** [comment]
刚刚试了换到QT版，能用了.......估计我也等它自己恢复吧。
