### ISSUE TITLE
能否添加一个小白卡7天自动领钢镚的功能

### ISSUE THREAD

**Issue by hshujun** [CaoZ/JD-Coin#18]

**Comment by CaoZ** [comment]
你好，这个功能现在已经有了~

https://github.com/CaoZ/JD-Coin/blob/4a3e1e686974880cffdf182d6907f987f064151d/app/job/daka.py#L170-L180

**Comment by hshujun** [comment]
谢谢~

**Comment by AdamChrist** [comment]
@CaoZ 7月23号的时候我小白卡签到了7天..好像不会自动领取哦..我是自己又去领的..

**Comment by hshujun** [comment]
第七天确实不会自动领取, 不知道第八天会不会领

**Comment by CaoZ** [comment]
![自动领](https://user-images.githubusercontent.com/1962293/28766786-add22692-7603-11e7-9679-4b1746312245.png)

```python
if not sign_success and as_json['resultCode'] == '0003':
    # 已打卡 7 次, 需要先去 "任务" 里完成领一个钢镚的任务...
    self.logger.info('已打卡 7 次, 去完成领钢镚任务...')
```
https://github.com/CaoZ/JD-Coin/blob/4a3e1e686974880cffdf182d6907f987f064151d/app/job/daka.py#L170-L180

第八天会自动领的，不先领取这一个钢镚的话继续打卡会失败。

**Comment by AdamChrist** [comment]
@CaoZ 原来如此..我每次看到不领,就自己去领了...
