### ISSUE TITLE
LogInError('登录 QQ 失败: 提交参数错误，请检查。(1604321868)',)

### ISSUE THREAD

**Issue by AdamChrist** [CaoZ/JD-Coin#19]
使用的是"方式一",现在无法登录QQ了,也没有办法签到

**Comment by gucheen** [comment]
这是因为 [qqlib](https://github.com/gera2ld/qqlib) 使用的登陆接口已经改了，要看这个库什么时候能修复 @AdamChrist

**Comment by CaoZ** [comment]
对, 可能是因为 QQ 的登录方式改了~ => https://github.com/gera2ld/qqlib/issues/23
幸好还有个内置浏览器的方式登录...

**Comment by riverai** [comment]
QT登录方法也可以自动填充用户名和密码，和QQ登录方法比起来实际没什么区别（区别很小）
