### ISSUE TITLE
活动好像结束了

### ISSUE THREAD

**Issue by wby238** [CaoZ/JD-Coin#21]
```log
jobs[red_packet] INFO: 领取结果: 本次活动已结束~

= 失败的任务: ['京东小金库现金红包']
```
最近打开好几次都是这样

**Comment by knva** [comment]
我这边还提示qq登录失败.

**Comment by CaoZ** [comment]
@wby238 对, 那个活动结束了, 可以先在配置文件中 [跳过这个任务](https://github.com/CaoZ/JD-Coin#%E6%88%91%E6%B2%A1%E6%9C%89%E5%B0%8F%E7%99%BD%E5%8D%A1%E6%88%91%E6%83%B3%E8%B7%B3%E8%BF%87%E6%9F%90%E4%BA%9B%E4%BB%BB%E5%8A%A1), 等下次更新时我再改下~

@knva 可能是因为 QQ 的登录方式改了~ => https://github.com/gera2ld/qqlib/issues/23
切换成浏览器方式登录就行了~ => https://github.com/CaoZ/JD-Coin#%E6%96%B9%E5%BC%8F%E4%BA%8C
