### ISSUE TITLE
help 使用 QT 方式登录时的报错

### ISSUE THREAD

**Issue by UncleThree** [CaoZ/JD-Coin#24]
mac 系统
python版本 pyenv 方式安装的 3.6.2

QQ登录方式不成功
选择使用QT方式登录时，python 意外退出，浏览器窗口打开失败

返回的错误信息如下
```
.pyenv/versions/3.6.2/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format,  format_regex))
ValueError: time data 'Sat, 09-Sep-2017 13:02:50 GMT' does not match format '%a, %d-%b-%Y %H:%M:%S GMT' ... re.compile('(?P<a>\\一|\\二|\\三|\\四|\\五|\\六|\\日),\\s+(?P<d>3[0-1]|[1-2]\\d|0[1-9]|[1-9]| [1-9])-(?P<b>\\ 1|\\ 2|\\ 3|\\ 4|\\ 5|\\ 6|\\ 7|\\ 8|\\ 9|10|11|12)-(?P<Y>\\d\\d\\d\\d)\\s+(?P<H>2[0-3]|[0-1]\\d|\\d):(?P<M>, re.IGNORECASE)
```
Sat, 09-Sep-2017 13:02:50 GMT
format_regex 是输出的新的打印，其中匹配星期部分 %a 是走了 中文星期的配置。

有没有遇到相似情况的朋友
**系统环境下时间匹配问题，该从何处下手解决？**

**Comment by AdamChrist** [comment]
应该是跟我一样的问题 ,目前知道是把语言改成英文就没有问题了..
https://github.com/CaoZ/JD-Coin/issues/20

**Comment by gucheen** [comment]
```
export LC_CTYPE="zh_CN.utf-8"
```
加上这个环境变量就可以了

**Comment by AdamChrist** [comment]
@gucheen 通过你的启发,我设置了`export LC_ALL=en_US.UTF-8`
现在可以用啦 :tada::tada::tada:

**Comment by UncleThree** [comment]
Thanks 诸位，已解决该问题

**Comment by CaoZ** [comment]
原因已找到, 是因为 Qt 会默认使用系统区域设置, 导致了一些时间计算(格式匹配)上的冲突, 现在可以不用加额外的环境变量了~

http://doc.qt.io/qt-5/qcoreapplication.html#locale-settings
