### ISSUE TITLE
金融-每天打卡

### ISSUE THREAD

**Issue by ZengGui** [CaoZ/JD-Coin#25]
https://m.jr.jd.com/integrate/getUp/html/index.html

每天早上5-8打卡

**Comment by knva** [comment]
这个估计做不了,写个脚本自动点按钮吧.

**Comment by CaoZ** [comment]
做是可以做到, 不过感觉意义不大...

看网上说的, 万一哪天忘打了就被反撸一块钱... 好像还存在打了卡但领到的不足一元的情况; 每天付款的流程需要人来操作, 有些麻烦; 打卡需在8点前完成, 但是现在 QQ 登录的方式[暂时不能用了](https://github.com/CaoZ/JD-Coin/issues/19), 登录用的 cookie 存在过期的情况, 这就要求只能在具有图形化界面的系统上运行打卡程序, 光为了运行下这个程序就开电脑感觉有些不值...

综上, 现在不如直接用京东的 App 直接参加这个活动. 不过万一哪天弄出个能直接在手机上运行的版本倒可以考虑加上哈~
