### ISSUE TITLE
添加奖励

### ISSUE THREAD

**Issue by quericy** [CaoZ/JD-Coin#3]
京东客户端签到领京豆：
除了基础签到以外，还有个翻牌奖励0~10京豆

**Comment by CaoZ** [comment]
感谢提醒~ 代码已更新, 这个功能加上了~

**Comment by quericy** [comment]
@CaoZ 可以考虑添加任务时间间隔(随机/人工设置)，高频率请求多个签到接口可能会被京东纳入风控的风险

**Comment by CaoZ** [comment]
感谢提醒~ 好像京东还没对这个做风控, 加上后运行时间就长了, 先不加了吧~
