### ISSUE TITLE
ModuleNotFoundError: No module named 'pyquery'

### ISSUE THREAD

**Issue by Explorare** [CaoZ/JD-Coin#33]
### Environment: 
Windows 10 1709 build 16299.19
Python 3.6.3

### Commit with this issue
6d804e29fdec32b3a22c9add0772c47f17ffe365

### Error log:
```
> python main.py
2017-11-03 17:04:30,031 root[config] INFO: 使用配置文件 "config.json".
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from job import jobs_all
  File "C:\Users\Explorare\Documents\GitHub\JD-Coin\app\job\__init__.py", line 6, in <module>
    from .bean import Bean
  File "C:\Users\Explorare\Documents\GitHub\JD-Coin\app\job\bean.py", line 1, in <module>
    from pyquery import PyQuery
ModuleNotFoundError: No module named 'pyquery'
```

**Comment by CaoZ** [comment]
你好，这是因为引入了新的第三方库`pyquery`，安装下即可：`pip install -r requirements.txt` 或 `pip install pyquery`。

ps：我曾考虑到一些不熟悉 Python 的人遇到这种问题时会不知道怎么办，因此加了提示：https://github.com/CaoZ/JD-Coin/blob/6d804e29fdec32b3a22c9add0772c47f17ffe365/app/main.py#L100-L106
但是一不小心加错了位置（囧），没起到作用... 因此我把这个提交回退了~

**Comment by Explorare** [comment]
Thanks for your support. It works again.

**Comment by tharindulucky** [comment]
Follow this thread. Last soultion should work!
https://github.com/Jefferson-Henrique/GetOldTweets-python/issues/67
