### ISSUE TITLE
新的双签能否支持

### ISSUE THREAD

**Issue by fakers777** [CaoZ/JD-Coin#44]
京东app和京东金融都签完，有个双签领京豆 谢谢大神。
还有 多个账号怎么处理

**Comment by CaoZ** [comment]
你好，双签功能添加了~

暂时没有内置的多帐号支持哈，要是想支持多个帐号的话只能创建多个配置文件，分别运行... 配置文件说明 -> https://github.com/CaoZ/JD-Coin#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E

**Comment by fakers777** [comment]
谢谢，双签好像要下线了

**Comment by rebill** [comment]
双签要执行两次才能成功，因为双签依赖普通签到，能设置个先后顺序吗？这样不需要执行两次

**Comment by CaoZ** [comment]
@rebill 感谢反馈，之前顺序确实错了，我错把 DakaApp（京东客户端钢镚打卡）当做京东金融签到了，现已更正~
