### ISSUE TITLE
运行错误，如图

### ISSUE THREAD

**Issue by hyc1743** [CaoZ/JD-Coin#48]
我是在Ubuntu的VPS上跑的，为何会出现这种问题？求教
 root(@hyc-vps: /app# python main. py

2018-03-0618:57:09,215root[ config]INF:使用配置文件 config.son

 Traceback (most recent call Last)

 File main. py, Line 10, in <module

 from job import jobs -all

 File /root/app/job/--init--py, Line 6, in <module> from .bean import Bean

 File /root/app/job/bean. py, Line 4, in < module>

 from.daka import Daka

 File /root/app/job/daka. py, Line 5, in <module> import browser

 File /root/app/browser. py, Line 9, in <module>

 from Pyqt5. Qtgui import Qicon

 Importerror: LIBGL So1: cannot open shared object file: No such file or directory

**Comment by hyc1743** [comment]
在Windows电脑下运行正常，成功签到

**Comment by CaoZ** [comment]
你好，这应该是因为你的 vps 上没有图形环境导致 Qt 不能运行导致的，现在登录京东需要借助内置浏览器，这就需要图形环境了~

**Comment by fakers777** [comment]
如果用phantomjs 这种浏览器是否可以？

**Comment by zuosc** [comment]
@CaoZ   不能在VPS的话，岂不是很麻烦

**Comment by CaoZ** [comment]
@00364291 对那个不太了解哈...

**Comment by CaoZ** [comment]
@zuosc 是的，无图形环境的时候登录有点麻烦...
