### ISSUE TITLE
是否可以添加设置让用户自行选择要执行的任务？

### ISSUE THREAD

**Issue by wby238** [CaoZ/JD-Coin#5]
例如，我没有小白卡，因此不需要执行小白卡打卡签到。

**Comment by CaoZ** [comment]
感谢提醒~ 代码已更新, 现在可以设置跳过一个或多个任务了: README.md -> [我没有小白卡/我想跳过某些任务](https://github.com/CaoZ/JD-Coin#%E6%88%91%E6%B2%A1%E6%9C%89%E5%B0%8F%E7%99%BD%E5%8D%A1%E6%88%91%E6%83%B3%E8%B7%B3%E8%BF%87%E6%9F%90%E4%BA%9B%E4%BB%BB%E5%8A%A1)

**Comment by wby238** [comment]
thx
