### ISSUE TITLE
为何不用cookies直接登录？

### ISSUE THREAD

**Issue by zuosc** [CaoZ/JD-Coin#50]
我尝试在VPS上登录，发现QT5模块没法用。

所以看了下源码，然后把browser.py全部注释掉了，接着把本地的data/cookies  拷贝到VPS上。  就可以顺利执行了。

所以综合来说，用到QT5就是为了获取cookies。  为何不直接读取文件呢？

在VPS用QT5上还是太蛋疼了啊，就算是本地，安装了那么多依赖，也是累赘啊

**Comment by CaoZ** [comment]
你说的”直接读取文件“获得 cookies 是读哪个文件呢？京东的登录状态是有有效期的，可能一两天就过期了，又得重新登录，有时候还会让你填验证码，用 Qt 基本可以做到自动登录。依赖还好啦，一条命令全部装好，也算不上累赘...

**Comment by zuosc** [comment]
@CaoZ   比如用chrome登录，然后把cookies和一些头内容保存下来。  每次程序直接读取cookies文件就好了。

不过过一两天就过期了，这个我是不知道的。

稍微想了一下，可以接微信通知，如果掉线了，微信通知一下。  重新登录下就好。

对于我自己来说，在VPS上没法用图形界面，所以没法用QT5

**Comment by zuosc** [comment]
@CaoZ  或者说，可不可以定期刷下京东的接口，来刷新cookies。  

比如这个，https://github.com/joaopsys/AutoChronoGG/blob/master/chronogg.py  每次请求，就重新保存JWT凭据。

不过不知道京东的机制，允不允许这样了

**Comment by zuosc** [comment]
今天签到成功了一半失败了一半。   失败主要是vip.jd那里登录状态失效了。  

你那边也是这样么？

**Comment by CaoZ** [comment]
@zuosc 这应该就是因为 cookie 过期了，成功失败各一半是因为一个是京东手机版网页，一个是 PC 端网页，两者登录状态不共享。

**Comment by fakers777** [comment]
我在树莓派上没法安装pyqt 没有webenginekit组件，怎么办

**Comment by zuosc** [comment]
@00364291   意思就是没有图形界面。  和我问题一样，参考我的做法吧

**Comment by fakers777** [comment]
没有界面 cookie失效后搞不定，用什么方法保证一直有效?

**Comment by zuosc** [comment]
@00364291   我也在尝试如何才能不过期。  你要是找到办法了，可以分享一下~~

**Comment by fakers777** [comment]
@zuosc 我把browser 模块替换成了 chrome 登录，目前验证可行。能解决没有pyqt模块的问题

**Comment by zuosc** [comment]
@CaoZ @00364291    差点忘了说， 我按照一开始说的方法，在VPS上跑，每小时执行一遍。  10来天了，没掉线。。。。

我觉着海星~~

**Comment by fakers777** [comment]
我加了些其他功能，比如 京东金融流量，京东支付签到等。可能是执行太频繁了，有时候要验证码。

**Comment by fakers777** [comment]
@zuosc

**Comment by zuosc** [comment]
@00364291   这个应该和频率有关系的，你的频率是怎样的？   有些敏感的，限制会多一点。

顺便chrome模块，是不需要图形界面么

**Comment by fakers777** [comment]
@zuosc 使用chrome 无头模式。 还可以 执行一个linux命令，运行无界面程序。网上有方法

**Comment by zuosc** [comment]
@00364291   学习了学习了  竟然还可以这样玩

**Comment by morethink** [comment]
@azz212 
可否分享一下Chrome 登录的代码？
