### ISSUE TITLE
流量加油站每天也可以签到领流量,可不可以考虑加到自动签到任务里

### ISSUE THREAD

**Issue by DanielXRecord** [CaoZ/JD-Coin#6]

**Comment by CaoZ** [comment]
感谢提醒~ 这个功能加进去了，但在默认配置文件（config.default.json）中是跳过的（流量太多了用不完了... 还是京豆和钢镚实惠啊~）。要是这个任务没有运行的话将它从`jobs_skip`中去掉即可。反之将它添加到`jobs_skip`中可跳过运行。

相关链接：[我没有小白卡/我想跳过某些任务](https://github.com/CaoZ/JD-Coin#%E6%88%91%E6%B2%A1%E6%9C%89%E5%B0%8F%E7%99%BD%E5%8D%A1%E6%88%91%E6%83%B3%E8%B7%B3%E8%BF%87%E6%9F%90%E4%BA%9B%E4%BB%BB%E5%8A%A1)
