### ISSUE TITLE
希望大佬添加功能：开启脚本后可以挂机每隔12小时运行一次

### ISSUE THREAD

**Issue by someash** [CaoZ/JD-Coin#66]
如题，懒得每天打开emmm

**Comment by fakers777** [comment]
可以使用一台机器定时任务 每天运行一次

**Comment by someash** [comment]
那用anaconda的应该怎么设置计划任务？

**Comment by CaoZ** [comment]
找到 Anaconda 中 Python 解释器可执行文件路径即可。

Windows 下可参考下这个回答 https://github.com/CaoZ/JD-Coin/issues/35, Mac 下用 launchctl 起个定时任务调用脚本即可，脚本可以这样写：

> #!/usr/bin/env bash
~/Dev/Envs/jd-env/bin/python3 ~/Dev/Code/JDCoin/app/main.py -c browser.json
read -p "Press any key to continue... " -n1 -s
exit
