### ISSUE TITLE
在Linux服务器终端上如何登陆？

### ISSUE THREAD

**Issue by julianhu1979** [CaoZ/JD-Coin#67]
在Linux服务器终端上如何登陆？跑了一下报ImportError: libGL.so.1: cannot open shared object file: No such file or directory错，应该是没有办法打开pyqt的浏览器导致的。

**Comment by CaoZ** [comment]
你好, 需要图形环境才能用, 现在京东登录有滑动验证了, 没有图形环境是很难登录的~
