### ISSUE TITLE
使用 PyQt5-5.11.2版本时报错

### ISSUE THREAD

**Issue by thanatos518** [CaoZ/JD-Coin#68]
请问，我在运行时报如下错误，应该如何处理呀。
File "C:\Users\Gilgamish\Desktop\python_tools\JD-Coin-browser\app\browser.py", line 11, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
运行环境
python              3.6
PyQt5               5.11.2
PyQt5-sip          4.19.12
pyquery             1.4.0
requests             2.18.3

**Comment by CaoZ** [comment]
是在 virtualenv 下运行的吗?

**Comment by thanatos518** [comment]
不是，是直接安装的。之前是可以用的，前几天我将python重装后就不行了，可能是PyQt5 5.11.2将QtWebEngineWidgets去掉了，我在对应目录下找不到QtWebEngineWidgets文件了。

**Comment by CaoZ** [comment]
嗯，重新安装 PyQt 应该就可以了~

**Comment by thanatos518** [comment]
重装了还是不行，还是报一样的错。

**Comment by thanatos518** [comment]
只在 python36\Lib\site-packages\PyQt5\uic\widget-plugins下能找到qtwebenginewidgets.py文件。

**Comment by thanatos518** [comment]
@CaoZ  我将PyQt5 5.11.2换成PyQt5 5.10.1就不报这个错了，请检查一下是否兼容PyQt5 5.11.2。

**Comment by CaoZ** [comment]
代码更新了吗？这个问题修复过了：https://github.com/CaoZ/JD-Coin/issues/62

**Comment by thanatos518** [comment]
@CaoZ  9月18号才下载的代码。

**Comment by CaoZ** [comment]
好的，晚上我试下哈，在 Mac 上是没问题的...

**Comment by thanatos518** [comment]
@CaoZ 好的，谢谢了。

**Comment by i-sync** [comment]
我刚才也在WIN下遇到了这个问题, 
好像32位的python 安装PyQt5时不包含`QtWebEngineWidgets` , 卸载32位的python, 重新安装64位的python 即可.
链接: [https://www.riverbankcomputing.com/software/pyqt/download5](https://www.riverbankcomputing.com/software/pyqt/download5)  
> Note that for v5.11 and later the 32-bit Windows wheels do not contain the WebEngine modules.

**Comment by thanatos518** [comment]
@i-sync 好的，谢谢了。

**Comment by getcode2git** [comment]
建议使用低版本的，新版的用其他类名进行替代了，指定版本可以，我用的是
PyQt5==5.8.1.1

**Comment by thanatos518** [comment]
@getcode2git 谢谢你了
