### ISSUE TITLE
发现京东股票也能领取京豆

### ISSUE THREAD

**Issue by riverai** [CaoZ/JD-Coin#7]
https://m.jr.jd.com/udc-active/2017/stockSign/html/index.html?environment=jdstock&appVersion=1.5.9&from=singlemessage&isappinstalled=1

存在7天连续领取翻倍奖励。

**Comment by CaoZ** [comment]
感谢提醒~

周末看了下发现领取京豆的逻辑比较简单，但是其中一个关键参数 `sid `不好获取，这个领取页面调用京东股票 App 的登录功能（`JRLoginView`）来完成登录，然后将用户的`pin`（估计是用户 id 之类的）加密后传递给页面用于后续操作。用 dex2jar 反编译了下京东股票的安卓客户端，但可能反编译的不完全，有些相关的代码没有看到，因此暂时不清楚这个`sid`的具体生成逻辑，所以这个功能暂时做不了了，等以后有机会再深入研究一下~~

**Comment by riverai** [comment]
闹着玩的，哈哈
